version: "1.0"

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - pg14Db:/var/lib/postgresql/data

  # server:
  #   image: xvii-server
  #   build: ./server
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - log:/var/log/server

  # client:
  #   image: xvii-client
  #   build: ./client
  #   ports: 
  #     - 3000:3000

volumes:
  pg14Db:
    driver: local
  log:
    driver: local
