version: "1.0"

services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      # dev values, will eventually replace with docker secrets
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev_db
      - POSTGRES_PASSWORD=password
    volumes:
      - pg14Db:/var/lib/postgresql/data

  server:
    image: xvii-server
    build: ./server
    environment:
      # dev values, will eventually replace with docker secrets
      - SESSION_JWT_SECRET=cef5c4791b7bfe28ba04d99fe2935f19b516ab8a65dd0a0b009991a53d9707f4
      - DB_CONNECT_DEV=postgres://dev:password@db:5432/dev_db
      - ENVIRONMENT=dev_stack
    ports:
      - 5000:5000
    volumes:
      - log:/var/log/server

  # client:
  #   image: xvii-client
  #   build: ./client
  #   ports: 
  #     - 3000:3000

volumes:
  pg14Db:
    driver: local
  log:
    driver: local
